/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package krpg

import krpg.core.KRPG

class App {
    private var krpg: KRPG? = null

    fun run() {
        this.krpg?.end()
        this.krpg = KRPG()
        this.krpg?.run()
    }
}

fun main() {
    val app: App = App()
    app.run()
}
